/******************************************************************************

                              Online C++ Compiler.
               Code, Compile, Run and Debug C++ program online.
Write your code in this editor and press "Run" button to compile and execute it.

*******************************************************************************/

#include <iostream>

using namespace std;

int main()
{
   int n ,m ;
   cin>>n>>m;
     
   cout<<(n==m ?"Yes":"No");
    return 0;
}
